apiVersion: v1
kind: Service
metadata:
  name: hospitality-service
spec:
  type: NodePort
  selector:
    app: hospitality
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007